model:
  # denoiser
  height: 64  
  in_channel: 3
  out_channel: 3
  time_embed: 128
  groups: 32
  dropout: 0.1
  mults: [1, 2, 4, 8]
  blocks: 2
  with_attn_height: [16, 8] 

  # diffusion
  timesteps: 1000
  objective: 'pred_noise' 
  conditional: false
  solver: 'base'  

train:
  # init
  init_method: 'kaiming' 

  # noise schedule
  noise_schedule: {
    'linear_start': 0.0001,
    'linear_end': 0.02,
    'schedule': 'linear'  # 'linear', 'cosine', 'quad', 'warmup10', 'warmup50'
  }

  # training parameters
  optimizer: 'Adam'  # 'Adam', 'AdamW'
  lr: 0.0001
  lr_schedule: 'MultiStepLR'  # 'MultiStepLR', 'CosineAnnealingLR'
  grad_clip: 1.0
  epochs: 10
  batch_size: 16
  num_data_workers: 6

  pretrained: false

  save_epoch_freq: 5


test:
  noise_schedule: {
    'linear_start': 0.0001,
    'linear_end': 0.02,
    'schedule': 'linear'  # 'linear', 'cosine', 'quad', 'warmup10', 'warmup50'
  }

path:
  path_ckp: './checkpoints'
